CREATE TABLE `COMPANYS` (
    `COMPANY_NAME_PK` VARCHAR(20) NOT NULL,
    `COMPANY_NAME` VARCHAR(20) NULL,
    PRIMARY KEY (`COMPANY_NAME_PK`)
);

CREATE TABLE `CARS` (
    `CAR_NAME_PK` VARCHAR(20) NOT NULL,
    `COMPANY_NAME_FK` VARCHAR(20) NOT NULL,
    `CAR_NAME` VARCHAR(20) NULL,
    PRIMARY KEY (`CAR_NAME_PK`),
    INDEX (`COMPANY_NAME_FK`)
);

CREATE TABLE `YEARS` (
    `YEAR_PK` VARCHAR(20) NOT NULL,
    `YEAR` VARCHAR(20) NULL,
    PRIMARY KEY (`YEAR_PK`)
);

CREATE TABLE `OPTIONS` (
    `OPTIONS_PK` VARCHAR(20) NOT NULL,
    `OPTION` VARCHAR(20) NULL,
    PRIMARY KEY (`OPTIONS_PK`)
);

CREATE TABLE `OPTIONDEATIALS` (
    `OPTIONS_DETAILS_PK` VARCHAR(20) NOT NULL,
    `CAR_NAME_FK` VARCHAR(20) NOT NULL,
    `YEAR_FK` VARCHAR(20) NOT NULL,
    `OPTIONS_FK` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`OPTIONS_DETAILS_PK`, `CAR_NAME_FK`, `YEAR_FK`, `OPTIONS_FK`),
    INDEX (`CAR_NAME_FK`),
    INDEX (`YEAR_FK`),
    INDEX (`OPTIONS_FK`)
);

ALTER TABLE `CARS` 
ADD CONSTRAINT `FK_COMPANYS_TO_CARS` 
FOREIGN KEY (`COMPANY_NAME_FK`)
REFERENCES `COMPANYS` (`COMPANY_NAME_PK`);

ALTER TABLE `OPTIONDEATIALS` 
ADD CONSTRAINT `FK_CARS_TO_OPTIONDEATIALS` 
FOREIGN KEY (`CAR_NAME_FK`)
REFERENCES `CARS` (`CAR_NAME_PK`);

ALTER TABLE `OPTIONDEATIALS` 
ADD CONSTRAINT `FK_YEARS_TO_OPTIONDEATIALS` 
FOREIGN KEY (`YEAR_FK`)
REFERENCES `YEARS` (`YEAR_PK`);

ALTER TABLE `OPTIONDEATIALS` 
ADD CONSTRAINT `FK_OPTIONS_TO_OPTIONDEATIALS` 
FOREIGN KEY (`OPTIONS_FK`)
REFERENCES `OPTIONS` (`OPTIONS_PK`);
