SELECT * FROM Employees E
LEFT JOIN ORDERS O
ON O.EMPLOYEEID = E.EMPLOYEEID
WHERE O.EMPLOYEEID IS NULL
;

SELECT E.EMPLOYEEID , COUNT(E.EMPLOYEEID) AS '주문받은 횟수' FROM EMPLOYEES E
LEFT JOIN ORDERS O 
ON O.EMPLOYEEID = E.EMPLOYEEID
GROUP BY E.EMPLOYEEID;